/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppSystemLogsRouteImport } from './routes/_app/system-logs'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppFailedTransactionsRouteImport } from './routes/_app/failed-transactions'
import { Route as AppCommissionsRouteImport } from './routes/_app/commissions'
import { Route as AppAuditLogsRouteImport } from './routes/_app/audit-logs'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppTerminalsIndexRouteImport } from './routes/_app/terminals/index'
import { Route as AppMerchantsIndexRouteImport } from './routes/_app/merchants/index'
import { Route as AppTerminalsTerminalIdRouteImport } from './routes/_app/terminals/$terminalId'
import { Route as AppMerchantsMerchantIdRouteImport } from './routes/_app/merchants/$merchantId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemLogsRoute = AppSystemLogsRouteImport.update({
  id: '/system-logs',
  path: '/system-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppFailedTransactionsRoute = AppFailedTransactionsRouteImport.update({
  id: '/failed-transactions',
  path: '/failed-transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalsIndexRoute = AppTerminalsIndexRouteImport.update({
  id: '/terminals/',
  path: '/terminals/',
  getParentRoute: () => AppRoute,
} as any)
const AppMerchantsIndexRoute = AppMerchantsIndexRouteImport.update({
  id: '/merchants/',
  path: '/merchants/',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalsTerminalIdRoute = AppTerminalsTerminalIdRouteImport.update({
  id: '/terminals/$terminalId',
  path: '/terminals/$terminalId',
  getParentRoute: () => AppRoute,
} as any)
const AppMerchantsMerchantIdRoute = AppMerchantsMerchantIdRouteImport.update({
  id: '/merchants/$merchantId',
  path: '/merchants/$merchantId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/commissions': typeof AppCommissionsRoute
  '/failed-transactions': typeof AppFailedTransactionsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/system-logs': typeof AppSystemLogsRoute
  '/transactions': typeof AppTransactionsRoute
  '/users': typeof AppUsersRoute
  '/merchants/$merchantId': typeof AppMerchantsMerchantIdRoute
  '/terminals/$terminalId': typeof AppTerminalsTerminalIdRoute
  '/merchants/': typeof AppMerchantsIndexRoute
  '/terminals/': typeof AppTerminalsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/commissions': typeof AppCommissionsRoute
  '/failed-transactions': typeof AppFailedTransactionsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/system-logs': typeof AppSystemLogsRoute
  '/transactions': typeof AppTransactionsRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/merchants/$merchantId': typeof AppMerchantsMerchantIdRoute
  '/terminals/$terminalId': typeof AppTerminalsTerminalIdRoute
  '/merchants': typeof AppMerchantsIndexRoute
  '/terminals': typeof AppTerminalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/failed-transactions': typeof AppFailedTransactionsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/system-logs': typeof AppSystemLogsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/merchants/$merchantId': typeof AppMerchantsMerchantIdRoute
  '/_app/terminals/$terminalId': typeof AppTerminalsTerminalIdRoute
  '/_app/merchants/': typeof AppMerchantsIndexRoute
  '/_app/terminals/': typeof AppTerminalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/analytics'
    | '/audit-logs'
    | '/commissions'
    | '/failed-transactions'
    | '/reports'
    | '/settings'
    | '/system-logs'
    | '/transactions'
    | '/users'
    | '/merchants/$merchantId'
    | '/terminals/$terminalId'
    | '/merchants/'
    | '/terminals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alerts'
    | '/analytics'
    | '/audit-logs'
    | '/commissions'
    | '/failed-transactions'
    | '/reports'
    | '/settings'
    | '/system-logs'
    | '/transactions'
    | '/users'
    | '/'
    | '/merchants/$merchantId'
    | '/terminals/$terminalId'
    | '/merchants'
    | '/terminals'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/alerts'
    | '/_app/analytics'
    | '/_app/audit-logs'
    | '/_app/commissions'
    | '/_app/failed-transactions'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/system-logs'
    | '/_app/transactions'
    | '/_app/users'
    | '/_app/'
    | '/_app/merchants/$merchantId'
    | '/_app/terminals/$terminalId'
    | '/_app/merchants/'
    | '/_app/terminals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-logs': {
      id: '/_app/system-logs'
      path: '/system-logs'
      fullPath: '/system-logs'
      preLoaderRoute: typeof AppSystemLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/failed-transactions': {
      id: '/_app/failed-transactions'
      path: '/failed-transactions'
      fullPath: '/failed-transactions'
      preLoaderRoute: typeof AppFailedTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminals/': {
      id: '/_app/terminals/'
      path: '/terminals'
      fullPath: '/terminals/'
      preLoaderRoute: typeof AppTerminalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/merchants/': {
      id: '/_app/merchants/'
      path: '/merchants'
      fullPath: '/merchants/'
      preLoaderRoute: typeof AppMerchantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminals/$terminalId': {
      id: '/_app/terminals/$terminalId'
      path: '/terminals/$terminalId'
      fullPath: '/terminals/$terminalId'
      preLoaderRoute: typeof AppTerminalsTerminalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/merchants/$merchantId': {
      id: '/_app/merchants/$merchantId'
      path: '/merchants/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof AppMerchantsMerchantIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppFailedTransactionsRoute: typeof AppFailedTransactionsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSystemLogsRoute: typeof AppSystemLogsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMerchantsMerchantIdRoute: typeof AppMerchantsMerchantIdRoute
  AppTerminalsTerminalIdRoute: typeof AppTerminalsTerminalIdRoute
  AppMerchantsIndexRoute: typeof AppMerchantsIndexRoute
  AppTerminalsIndexRoute: typeof AppTerminalsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppFailedTransactionsRoute: AppFailedTransactionsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSystemLogsRoute: AppSystemLogsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppMerchantsMerchantIdRoute: AppMerchantsMerchantIdRoute,
  AppTerminalsTerminalIdRoute: AppTerminalsTerminalIdRoute,
  AppMerchantsIndexRoute: AppMerchantsIndexRoute,
  AppTerminalsIndexRoute: AppTerminalsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
